[package]
name = "borsholder"
version = "0.1.0"
authors = ["kennytm <kennytm@gmail.com>"]
description = "Dashboard of rust-lang/rust's bors queue."
license = "MIT"

[dependencies]
ammonia = "1.0.0-rc1"
chrono = { version = "0.4", features = ["serde"] }
chrono-humanize = "0.0.10"
error-chain = "0.10"    # tera 0.10 depends on error-chain 0.10.
futures = "0.1"
hyper = "0.11"
kuchiki = "0.6"
lazy_static = "0.2"
log = "0.3"
maplit = "0.1"
markup5ever = "0.5"
reqwest = "0.8"
serde = "1"
serde_derive = "1"
serde_json = "1"
structopt = "0.1"
structopt-derive = "0.1"
tera = "0.10"

[[bin]]
name = "borsholder"
