[package]
name = "borsholder"
version = "0.4.0"
authors = ["kennytm <kennytm@gmail.com>"]
description = "Dashboard of rust-lang/rust's bors queue."
license = "MIT"
repository = "https://github.com/kennytm/borsholder"
keywords = ["bors", "homu"]
readme = "README.md"

[badges]
travis-ci = { repository = "kennytm/borsholder" }
is-it-maintained-issue-resolution = { repository = "kennytm/borsholder" }
is-it-maintained-open-issues = { repository = "kennytm/borsholder" }
maintenance = { status = "actively-developed" }

[dependencies]
ammonia = "1.0.0-rc3"
chrono = { version = "0.4", features = ["serde"] }
chrono-humanize = "0.0.10"
env_logger = "0.4"
error-chain = "0.10"    # tera 0.10 depends on error-chain 0.10.
futures = "0.1"
hyper = "0.11"
kuchiki = "0.6"
lazy_static = "0.2"
log = "0.3"
maplit = "1"
markup5ever = "0.5"     # kuchiki 0.6 depends on html5ever 0.20 which depends on markup5ever 0.5
mime = "0.3"
regex = "0.2"
relative-path = "0.1"
reqwest = "0.8"
serde = "1"
serde_derive = "1"
structopt = "0.1"
structopt-derive = "0.1.4"
tera = "0.10"

[[bin]]
name = "borsholder"
