stringify![

query ($owner: String!, $repo: String!, $after: String) {
  repository(owner: $owner, name: $repo) {
    pullRequests(first: 100, after: $after, states: [OPEN], orderBy: {field: UPDATED_AT, direction: DESC}) {
      pageInfo {
        endCursor
        hasNextPage
      }
      nodes {
        author {
          login
        }
        createdAt
        updatedAt
        mergeable
        number
        title
        additions
        deletions
        labels(first: 10) {
          nodes {
            name
            color
          }
        }
        commits(last: 1) {
          nodes {
            commit {
              status {
                contexts {
                  context
                  description
                  targetUrl
                  state
                }
              }
            }
          }
        }
      }
    }
  }
}

]