stringify![

query ($owner: String!, $repo: String!, $after: String) {
  repository(owner: $owner, name: $repo) {
    pullRequests(first: 99, after: $after, states: [OPEN]) {
      //# Cost of requesting 99 PRs is 1, and cost of requesting 100 PRs is 2. Don't know why.
      pageInfo {
        endCursor
        hasNextPage
      }
      nodes {
        author {
          login
        }
        createdAt
        updatedAt
        mergeable
        number
        title
        additions
        deletions
        baseRefName
        headRefName
        body
        labels(first: 10) {
          nodes {
            name
            color
          }
        }
        commits(last: 1) {
          nodes {
            commit {
              checkSuites(first: 3) {
                nodes {
                  checkRuns(first: 5) {
                    nodes {
                      name
                      title
                      permalink
                      conclusion
                    }
                  }
                }
              }
              status {
                contexts {
                  context
                  description
                  targetUrl
                  state
                }
              }
            }
          }
        }
      }
    }
  }
}

]
